# Generated by Django 3.2.13 on 2022-04-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20220413_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exercises',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
