# Generated by Django 3.2.13 on 2022-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20220425_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='weight',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
