# Generated by Django 3.2.13 on 2022-04-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_lift_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='user_profile',
            new_name='owner',
        ),
    ]
