# Generated by Django 3.2.13 on 2022-04-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_rename_user_profile_lift_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='owner',
            new_name='user_profile',
        ),
    ]
